AWSTemplateFormatVersion: "2010-09-09"
Description: This CloudFormation template provisions the resources required to connect to AWS account

Resources:
  ################ Congito #######################

  CognitoIdentityPoolUnauthRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: "sts:AssumeRoleWithWebIdentity"
            Condition:
              "ForAnyValue:StringLike":
                "cognito-identity.amazonaws.com:amr": unauthenticated
            Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
        Version: 2012-10-17

  CognitoIdentityPoolUnauthRoleIamPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - "geo:GetPlace"
              - "geo:SearchPlaceIndex*"
              - "geo:GetMap*"
              - "geo:CalculateRoute"
            Effect: Allow
            Resource:
              - !Sub "arn:aws:geo:${AWS::Region}:${AWS::AccountId}:map/location.aws.com.demo.maps.Grab.StandardLight"
              - !Sub "arn:aws:geo:${AWS::Region}:${AWS::AccountId}:map/location.aws.com.demo.maps.Grab.StandardDark"
              - !Sub "arn:aws:geo:${AWS::Region}:${AWS::AccountId}:place-index/location.aws.com.demo.places.Grab.PlaceIndex"
              - !Sub "arn:aws:geo:${AWS::Region}:${AWS::AccountId}:route-calculator/location.aws.com.demo.routes.Grab.RouteCalculator"
        Version: 2012-10-17
      PolicyName: !Sub "CognitoIdentityPoolUnauthRoleIamPolicy-${AWS::StackName}"
      Roles:
        - !Ref CognitoIdentityPoolUnauthRole

  CognitoIdentityPool:
    Type: "AWS::Cognito::IdentityPool"
    Properties:
      AllowUnauthenticatedIdentities: true
      AllowClassicFlow: true

  CognitoIdentityPoolDefaultRoleAttachment:
    Type: "AWS::Cognito::IdentityPoolRoleAttachment"
    Properties:
      IdentityPoolId: !Ref CognitoIdentityPool
      Roles:
        unauthenticated: !GetAtt
          - CognitoIdentityPoolUnauthRole
          - Arn

  AmazonLocationDemoMapsGrabStandardLight:
    Type: AWS::Location::Map
    Properties:
      Configuration:
        Style: VectorGrabStandardLight
      Description: You created this resource by running Amazon Location Demo's CloudFormation template.
      MapName: location.aws.com.demo.maps.Grab.StandardLight

  AmazonLocationDemoMapsGrabStandardDark:
    Type: AWS::Location::Map
    Properties:
      Configuration:
        Style: VectorGrabStandardDark
      Description: You created this resource by running Amazon Location Demo's CloudFormation template.
      MapName: location.aws.com.demo.maps.Grab.StandardDark

  AmazonLocationDemoPlaceIndexGrab:
    Type: AWS::Location::PlaceIndex
    Properties:
      DataSource: Grab
      Description: You created this resource by running Amazon Location Demo's CloudFormation template.
      IndexName: location.aws.com.demo.places.Grab.PlaceIndex

  AmazonLocationDemoRouteGrab:
    Type: AWS::Location::RouteCalculator
    Properties:
      CalculatorName: location.aws.com.demo.routes.Grab.RouteCalculator
      DataSource: Grab
      Description: You created this resource by running Amazon Location Demo's CloudFormation template.

Outputs:
  Region:
    Value: !Sub "${AWS::Region}"

  IdentityPoolId:
    Value: !Ref CognitoIdentityPool
