AWSTemplateFormatVersion: '2010-09-09'
Description: This CloudFormation template provisions the resources required to connect to AWS account

Resources:

  ################ Congito #######################

  CognitoIdentityPoolUnauthRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRoleWithWebIdentity'
            Condition:
              'ForAnyValue:StringLike':
                'cognito-identity.amazonaws.com:amr': unauthenticated
            Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
        Version: 2012-10-17

  CognitoIdentityPoolUnauthRoleIamPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - "geo:GetPlace"
              - "geo:SearchPlaceIndex*"
              - "geo:GetMap*"
              - "geo:CalculateRoute"
            Effect: Allow
            Resource: 
              - !Sub 'arn:aws:geo:${AWS::Region}:${AWS::AccountId}:map/location.aws.com.demo.maps.Esri.Light'
              - !Sub 'arn:aws:geo:${AWS::Region}:${AWS::AccountId}:map/location.aws.com.demo.maps.Esri.DarkGrayCanvas'
              - !Sub 'arn:aws:geo:${AWS::Region}:${AWS::AccountId}:map/location.aws.com.demo.maps.Esri.Imagery'
              - !Sub 'arn:aws:geo:${AWS::Region}:${AWS::AccountId}:map/location.aws.com.demo.maps.Esri.LightGrayCanvas'
              - !Sub 'arn:aws:geo:${AWS::Region}:${AWS::AccountId}:map/location.aws.com.demo.maps.Esri.Navigation'
              - !Sub 'arn:aws:geo:${AWS::Region}:${AWS::AccountId}:map/location.aws.com.demo.maps.Esri.Streets'
              - !Sub 'arn:aws:geo:${AWS::Region}:${AWS::AccountId}:map/location.aws.com.demo.maps.HERE.Explore'
              - !Sub 'arn:aws:geo:${AWS::Region}:${AWS::AccountId}:map/location.aws.com.demo.maps.HERE.Contrast'
              - !Sub 'arn:aws:geo:${AWS::Region}:${AWS::AccountId}:map/location.aws.com.demo.maps.HERE.ExploreTruck'
              - !Sub 'arn:aws:geo:${AWS::Region}:${AWS::AccountId}:map/location.aws.com.demo.maps.HERE.Hybrid'
              - !Sub 'arn:aws:geo:${AWS::Region}:${AWS::AccountId}:map/location.aws.com.demo.maps.HERE.Imagery'
              - !Sub 'arn:aws:geo:${AWS::Region}:${AWS::AccountId}:map/location.aws.com.demo.maps.Grab.StandardLight'
              - !Sub 'arn:aws:geo:${AWS::Region}:${AWS::AccountId}:map/location.aws.com.demo.maps.Grab.StandardDark'
              - !Sub 'arn:aws:geo:${AWS::Region}:${AWS::AccountId}:place-index/location.aws.com.demo.places.Esri.PlaceIndex'
              - !Sub 'arn:aws:geo:${AWS::Region}:${AWS::AccountId}:place-index/location.aws.com.demo.places.HERE.PlaceIndex'
              - !Sub 'arn:aws:geo:${AWS::Region}:${AWS::AccountId}:place-index/location.aws.com.demo.places.Grab.PlaceIndex'
              - !Sub 'arn:aws:geo:${AWS::Region}:${AWS::AccountId}:route-calculator/location.aws.com.demo.routes.Esri.RouteCalculator'
              - !Sub 'arn:aws:geo:${AWS::Region}:${AWS::AccountId}:route-calculator/location.aws.com.demo.routes.HERE.RouteCalculator'
              - !Sub 'arn:aws:geo:${AWS::Region}:${AWS::AccountId}:route-calculator/location.aws.com.demo.routes.Grab.RouteCalculator'
        Version: 2012-10-17
      PolicyName: !Sub 'CognitoIdentityPoolUnauthRoleIamPolicy-${AWS::StackName}'
      Roles:
        - !Ref CognitoIdentityPoolUnauthRole
        
  CognitoIdentityPool:
    Type: 'AWS::Cognito::IdentityPool'
    Properties:
      AllowUnauthenticatedIdentities: true
      AllowClassicFlow: true
      # CognitoIdentityProviders: 
      #   - ClientId: !Ref UserPoolClient
      #     ProviderName: !GetAtt UserPool.ProviderName

  CognitoIdentityPoolDefaultRoleAttachment:
    Type: 'AWS::Cognito::IdentityPoolRoleAttachment'
    Properties:
      IdentityPoolId: !Ref CognitoIdentityPool
      Roles:
        unauthenticated: !GetAtt 
          - CognitoIdentityPoolUnauthRole
          - Arn
          
  AmazonLocationDemoMapsEsriLight:
    Type: AWS::Location::Map
    Properties: 
      Configuration: 
        Style: VectorEsriTopographic
      Description: You created this resource by running Amazon Location Demo's CloudFormation template.
      MapName: location.aws.com.demo.maps.Esri.Light   

  AmazonLocationDemoMapsEsriStreets:  
    Type: AWS::Location::Map
    Properties: 
      Configuration: 
        Style: VectorEsriStreets
      Description: You created this resource by running Amazon Location Demo's CloudFormation template.
      MapName: location.aws.com.demo.maps.Esri.Streets

  AmazonLocationDemoMapsEsriDarkGrayCanvas:
    Type: AWS::Location::Map
    Properties: 
      Configuration: 
        Style: VectorEsriDarkGrayCanvas
      Description: You created this resource by running Amazon Location Demo's CloudFormation template.
      MapName: location.aws.com.demo.maps.Esri.DarkGrayCanvas

  AmazonLocationDemoMapsEsriImagery:
    Type: AWS::Location::Map
    Properties: 
      Configuration: 
        Style: RasterEsriImagery
      Description: You created this resource by running Amazon Location Demo's CloudFormation template.
      MapName: location.aws.com.demo.maps.Esri.Imagery

  AmazonLocationDemoMapsEsriLightGrayCanvas:
    Type: AWS::Location::Map
    Properties: 
      Configuration: 
        Style: VectorEsriLightGrayCanvas
      Description: You created this resource by running Amazon Location Demo's CloudFormation template.
      MapName: location.aws.com.demo.maps.Esri.LightGrayCanvas    

  AmazonLocationDemoMapsEsriNavigation:
    Type: AWS::Location::Map
    Properties: 
      Configuration: 
        Style: VectorEsriNavigation
      Description: You created this resource by running Amazon Location Demo's CloudFormation template.
      MapName: location.aws.com.demo.maps.Esri.Navigation

  AmazonLocationDemoMapsHere:
    Type: AWS::Location::Map
    Properties: 
      Configuration: 
        Style: VectorHereExplore
      Description: You created this resource by running Amazon Location Demo's CloudFormation template.
      MapName: location.aws.com.demo.maps.HERE.Explore

  AmazonLocationDemoMapsHereContrast:
    Type: AWS::Location::Map
    Properties: 
      Configuration: 
        Style: VectorHereContrast
      Description: You created this resource by running Amazon Location Demo's CloudFormation template.
      MapName: location.aws.com.demo.maps.HERE.Contrast     

  AmazonLocationDemoMapsHereExploreTruck:
    Type: AWS::Location::Map
    Properties: 
      Configuration: 
        Style: VectorHereExploreTruck
      Description: You created this resource by running Amazon Location Demo's CloudFormation template.
      MapName: location.aws.com.demo.maps.HERE.ExploreTruck

  AmazonLocationDemoMapsHereHybrid:
    Type: AWS::Location::Map
    Properties: 
      Configuration: 
        Style: HybridHereExploreSatellite
      Description: You created this resource by running Amazon Location Demo's CloudFormation template.
      MapName: location.aws.com.demo.maps.HERE.Hybrid

  AmazonLocationDemoMapsHereImagery:
    Type: AWS::Location::Map
    Properties: 
      Configuration: 
        Style: RasterHereExploreSatellite
      Description: You created this resource by running Amazon Location Demo's CloudFormation template.
      MapName: location.aws.com.demo.maps.HERE.Imagery

  AmazonLocationDemoMapsGrabLight:
    Type: AWS::Location::Map
    Properties: 
      Configuration: 
        Style: VectorGrabStandardLight
      Description: You created this resource by running Amazon Location Demo's CloudFormation template.
      MapName: location.aws.com.demo.maps.Grab.StandardLight

  AmazonLocationDemoMapsGrabLight:
    Type: AWS::Location::Map
    Properties: 
      Configuration: 
        Style: VectorGrabStandardDark
      Description: You created this resource by running Amazon Location Demo's CloudFormation template.
      MapName: location.aws.com.demo.maps.Grab.StandardDark

  AmazonLocationDemoPlaceIndexEsr:
    Type: AWS::Location::PlaceIndex
    Properties: 
      DataSource: Esri
      Description: You created this resource by running Amazon Location Demo's CloudFormation template.
      IndexName: location.aws.com.demo.places.Esri.PlaceIndex

  AmazonLocationDemoPlaceIndexHere:
    Type: AWS::Location::PlaceIndex
    Properties: 
      DataSource: Here
      Description: You created this resource by running Amazon Location Demo's CloudFormation template.
      IndexName: location.aws.com.demo.places.HERE.PlaceIndex

  AmazonLocationDemoPlaceIndexGrab:
    Type: AWS::Location::PlaceIndex
    Properties: 
      DataSource: Grab
      Description: You created this resource by running Amazon Location Demo's CloudFormation template.
      IndexName: location.aws.com.demo.places.Grab.PlaceIndex      

  AmazonLocationDemoRouteEsri:
    Type: AWS::Location::RouteCalculator
    Properties: 
      CalculatorName: location.aws.com.demo.routes.Esri.RouteCalculator
      DataSource: Esri
      Description: You created this resource by running Amazon Location Demo's CloudFormation template.

  AmazonLocationDemoRouteHere:
    Type: AWS::Location::RouteCalculator
    Properties: 
      CalculatorName: location.aws.com.demo.routes.HERE.RouteCalculator
      DataSource: Here
      Description: You created this resource by running Amazon Location Demo's CloudFormation template.

  AmazonLocationDemoRouteGrab:
    Type: AWS::Location::RouteCalculator
    Properties: 
      CalculatorName: location.aws.com.demo.routes.Grab.RouteCalculator
      DataSource: Grab
      Description: You created this resource by running Amazon Location Demo's CloudFormation template.      

Outputs:

  UserDomain:
    Value: !Sub 'https://${AWS::AccountId}.auth.${AWS::Region}.amazoncognito.com'

  IdentityPoolId:
    Value: !Ref CognitoIdentityPool
